### ISSUE TITLE
EMNIST dataset error

### ISSUE THREAD

**Issue by lunan0320** [orion-orion/FedAO#1]
When I want to set the dataset 'EMNIST' for federated learning, I found that RuntimeError: ECONNRESET: connection reset by peer.
What I changed is just the dataset name and log dir location.
Thanks .
## os
MAC book m1pro  
## python version
3.9.10
<img width="882" alt="image" src="https://github.com/orion-orion/FedAO/assets/68414485/be2734fa-dd3f-4638-b7ee-e0d352a0fd22">

**Comment by orion-orion** [comment]
Hello, `torch.distributed.rpc` module only supports the Linux operating system, so you must ensure that you run the relevant code on the Linux operating system, otherwise an error will be reported~ (see [GitHub issues: torch.distributed.rpc](https://github.com/iffiX/machin/issues/17))

**Comment by lunan0320** [comment]
thanks for your guidance @orion-orion,but  I learned that the module `rpc` is supported by MAC OS and Linux.There are always some strange problems when using this `rpc` framework

**Comment by orion-orion** [comment]
Haha, that's really weird.
